export const FIELD_SIZE = 5;
export const LETTERS_SHAKING_DURATION = 300;
export const LETTER_ROTATING_DURATION = 600;
export const LETTER_SELECTION_DELAY_FOR_BOT = 750;
export const LETTERS_ZOOM_DURATION = 200;
